import { router } from "expo-router";
import React from "react";
import {
  EggFried,
  Sun,
  Moon,
} from "lucide-react-native";
import {
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from "react-native";

import { useTheme } from "../context/ThemeContext";

const meals = [
  {
    day: "Monday",
    breakfast: "Oats & Banana Bowl",
    lunch: "Paneer Rice Bowl",
    dinner: "Dal, Roti & Salad",
  },
  {
    day: "Tuesday",
    breakfast: "Vegetable Poha",
    lunch: "Rajma Rice",
    dinner: "Paneer Roti Wrap",
  },
  {
    day: "Wednesday",
    breakfast: "Besan Chilla",
    lunch: "Chole Rice",
    dinner: "Vegetable Khichdi",
  },
  {
    day: "Thursday",
    breakfast: "Idli & Sambar",
    lunch: "Dal Tadka & Roti",
    dinner: "Paneer Bhurji",
  },
  {
    day: "Friday",
    breakfast: "Upma & Fruit",
    lunch: "Vegetable Pulao",
    dinner: "Dal & Roti",
  },
  {
    day: "Saturday",
    breakfast: "Aloo Paratha",
    lunch: "Chole & Roti",
    dinner: "Vegetable Soup",
  },
  {
    day: "Sunday",
    breakfast: "Dosa & Sambar",
    lunch: "Paneer Biryani",
    dinner: "Dal Khichdi",
  },
];

export default function MealPlanScreen() {
  const { colors } = useTheme();

  return (
    <View
      style={[
        styles.container,
        { backgroundColor: colors.background },
      ]}
    >
      {/* CONTENT */}
      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={styles.content}
      >
        <Text
          style={[
            styles.title,
            { color: colors.text },
          ]}
        >
          7-Day Meal Plan
        </Text>

        <Text
          style={[
            styles.subtitle,
            { color: colors.textSecondary },
          ]}
        >
          Your personalized weekly meals will be generated by the
          Meal Planner Agent after backend integration.
        </Text>

        {meals.map((meal) => (
          <View
            key={meal.day}
            style={[
              styles.dayCard,
              {
                backgroundColor: colors.card,
                borderColor: colors.border,
              },
            ]}
          >
            <Text
              style={[
                styles.dayTitle,
                { color: "#208AEF" },
              ]}
            >
              {meal.day}
            </Text>

            <MealRow
              icon="breakfast"
              label="Breakfast"
              meal={meal.breakfast}
              colors={colors}
            />

            <MealRow
              icon="lunch"
              label="Lunch"
              meal={meal.lunch}
              colors={colors}
            />

            <MealRow
              icon="dinner"
              label="Dinner"
              meal={meal.dinner}
              last
              colors={colors}
            />
          </View>
        ))}
      </ScrollView>
    </View>
  );
}

function MealRow({
  icon,
  label,
  meal,
  last = false,
  colors,
}: {
  icon: "breakfast" | "lunch" | "dinner";
  label: string;
  meal: string;
  last?: boolean;
  colors: any;
}) {
  const Icon =
    icon === "breakfast"
      ? EggFried
      : icon === "lunch"
        ? Sun
        : Moon;

  const iconColor =
    icon === "breakfast"
      ? "#F0A500"
      : icon === "lunch"
        ? "#F4B400"
        : "#6B62E8";

  return (
    <View
      style={[
        styles.mealRow,
        !last && styles.mealRowSpacing,
      ]}
    >
      <View
        style={[
          styles.iconContainer,
          {
            backgroundColor: colors.primaryLight,
          },
        ]}
      >
        <Icon
          size={22}
          color={iconColor}
          strokeWidth={2}
        />
      </View>

      <View style={styles.mealInfo}>
        <Text
          style={[
            styles.mealLabel,
            { color: colors.textMuted },
          ]}
        >
          {label}
        </Text>

        <Text
          style={[
            styles.mealName,
            { color: colors.text },
          ]}
        >
          {meal}
        </Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },

  /* CONTENT */

  content: {
    padding: 20,
    paddingTop: 28,
    paddingBottom: 40,
  },

  title: {
    fontSize: 29,
    fontWeight: "800",
    marginBottom: 7,
  },

  subtitle: {
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 20,
  },

  /* DAY CARD */

  dayCard: {
    borderRadius: 18,
    padding: 17,
    marginBottom: 14,
    borderWidth: 1,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },

  dayTitle: {
    fontSize: 19,
    fontWeight: "800",
    marginBottom: 15,
  },

  /* MEAL ROW */

  mealRow: {
    flexDirection: "row",
    alignItems: "center",
  },

  mealRowSpacing: {
    marginBottom: 16,
  },

  iconContainer: {
    width: 40,
    height: 40,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 11,
  },

  mealInfo: {
    flex: 1,
  },

  mealLabel: {
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
    marginBottom: 3,
  },

  mealName: {
    fontSize: 15,
    fontWeight: "700",
  },
});
